#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Usage: $0 folder [folder ..]" >&2
	exit 1
fi

END=0
for folder
do
	if [ ! -d "$folder" ]
	then
		echo "WARNING: $folder is not a folder. Omitting..." >&2
		END=2
		continue
	fi
	ARCH_GPX=`ls "$folder"/*.gpx 2>/dev/null | wc -l`
	if [ $ARCH_GPX -eq 0 ]
	then
		echo "WARNING: $folder does not contain .gpx files. Omitting..." >&2
		END=2
		continue
	fi
	echo "Removing GPS data from $folder..."
	exiftool -GPS:all= "$folder"
done

exit $END
