#!/bin/bash

SCRIPT=`readlink -f "$0"`
GPSPHOTO=`dirname "$SCRIPT"`/gpsPhoto.pl
REMOVE_GPS=`dirname "$SCRIPT"`/borrar_datos_gps

TIMEOFFSET=0

if [ ! -x $GPSPHOTO ]
then
	echo "Can't find gpsPhoto.pl or it is not executable" >&2
	exit 1
fi

if [ ! -x $REMOVE_GPS ]
then
	echo "Can't find the remove gps script or it is not executable" >&2
	exit 1
fi

for dir
do
	if [ ! -d "${dir}" ]
	then
		echo "$dir is not a directory" >&2
		exit 1
	fi
done


for dir
do
	echo "Working on ${dir}..."
	echo "Removing old GPS data on ${dir}..."
	$REMOVE_GPS "${dir}" | while read LINE
	do
		echo "    $LINE"
	done
	echo "geotagging ${dir}..."
	$GPSPHOTO --timeoffset "${TIMEOFFSET}" --maxtimediff 600 --dir "${dir}" --gpsdir "${dir}" >> "${dir}/geotag.log" 2>> ${dir}/geotag.err
	echo
	echo "Folder ${dir} done"
	echo
done

